<a href="https://colab.research.google.com/github/rosa2070/web1/blob/master/%EC%A0%9C%EC%A3%BC%ED%95%98%EA%B0%84%EB%94%94%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A7%88%EC%94%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

data = [1.1, 2, 3]

a = np.array(data)
a.dtype

dtype('float64')

In [ ]:
import numpy as np

data = [1.1, 2, 3]

a = np.array(data, dtype=np.float32)
a.dtype

dtype('float32')

In [ ]:
data = [1.1, 2, 3]

a = np.array(data, dtype=np.int32)
a.dtype
a

array([1, 2, 3], dtype=int32)

In [ ]:
data = [1.1, 2, 3]

a = np.array(data, dtype='i4')
a.dtype
a

array([1, 2, 3], dtype=int32)

In [ ]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a
a = np.int32(a)
a

array([1, 2, 3], dtype=int32)

In [ ]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a= a.astype(np.int64)
a

array([1, 2, 3])

In [ ]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a= a.astype(np.string_)
a

array([b'1.1', b'2.0', b'3.0'], dtype='|S32')

In [ ]:
a = np.uint16(0)
a.dtype
a = a - 1
a.dtype

dtype('int64')

In [ ]:
a = np.uint16(-1)
a

65535

#arange와 reshape_값의 호출(indexing, slicing)

In [ ]:
a= np.array([i for i in range(2, 11, 2)])
a

array([ 2,  4,  6,  8, 10])

In [ ]:
a= np.array(range(2,11,2))
a

array([ 2,  4,  6,  8, 10])

In [ ]:
np.arange(10)
np.arange(2, 11, 2)
np.arange(10, 15, .5)
np.arange(10, 2, -1)
np.arange(10, 2, -1.5)

array([10. ,  8.5,  7. ,  5.5,  4. ,  2.5])

In [ ]:
a = np.arange(10)
a.ndim
a.shape
a.size

10

In [ ]:
a = np.arange(40).reshape(2, 5, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [ ]:
a[0][1][1]

5

In [ ]:
a[1][2][1]

29

In [ ]:
a[-1][-3][-3]

29

In [ ]:
a[-1, -3, -3]

29

In [ ]:
a[1, 2, 1]

29

In [ ]:
a[a>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

#slicing

In [8]:
a = np.arange(30)
a

NameError: ignored

In [9]:
a[::-1]

NameError: ignored

In [ ]:
a[5:20:2] #a[start:stop:step]

In [ ]:
a = a.reshape(5, 6)
a

In [ ]:
a[:, 1]

In [ ]:
a[1,:]#a[1]

In [ ]:
a[:3, :3]

In [ ]:
a[::2, ::2]

In [ ]:
a

In [ ]:
b = a[::2, ::2]
b

In [ ]:
b[0] = 100
b

In [ ]:
b = a[::2, ::2].copy()
b

In [ ]:
b[0] = 1000
b

In [ ]:
a 

In [ ]:
a =np.arange(30).reshape(2, 5, 3)
a

In [ ]:
a[:,:,1]

In [ ]:
a[:,1,:]

In [ ]:
a[1,:,:]

In [ ]:
a[1,:,::-1]

#배열의 연결과 분할

In [ ]:
x = [1,2,3]
y = [4,5,6]

#np.array(x) + np.array(y)
a = np.array(x)
b = np.array(y)

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([a,b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

#np.concatenate([a,b,a,b])
np.concatenate([[a,b],[a,b]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
np.concatenate([a,b], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

#np.vstack([a,b]) #vertical stack
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
a = np.arange(15).reshape(3, 5)
b = np.arange(10, 20).reshape(2, 5)

np.vstack([a,b]) #vertical stack


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a =np.arange(10,121,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [7]:
np.split(a,[3,5,9,10])

NameError: ignored

In [12]:
import numpy as np
a = np.arange(10,121,10).reshape(3,4)
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [14]:
#np.vsplit(a,3)
np.hsplit(a,4)[0]

array([[10],
       [50],
       [90]])

#다양한 Matrix 만들기

In [15]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
import numpy as np
c = np.ones([3,4])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
c = np.ones([3,4,5])
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [4]:
c = np.zeros([3,4,5])
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
e = np.arange(9).reshape(3, 3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.dot(d, e)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [8]:
np.empty(10)

array([3.74959146e-316, 2.66795449e-322, 2.12199579e-314, 5.92440119e+169,
       1.41370696e+190, 1.32777395e-065, 2.54768670e+179, 4.82410907e+228,
       1.41463075e+190, 6.05457077e-310])

In [9]:
np.full((3,4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [11]:
np.linspace(2,10,6)


array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [12]:
np.linspace(2,100,10)

array([  2.        ,  12.88888889,  23.77777778,  34.66666667,
        45.55555556,  56.44444444,  67.33333333,  78.22222222,
        89.11111111, 100.        ])

In [13]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a.ravel(order='C') #행기준

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
a.ravel(order='F') #열기준

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

#유니버셜 함수

In [18]:
max(range(100))

99

In [19]:
min(range(100))

0

In [23]:
%%timeit

for i in range(10):
  max(range(1000000))

1 loop, best of 3: 289 ms per loop


In [24]:
%%timeit

for i in range(10):
    np.max(np.arange(1000000))

10 loops, best of 3: 20.8 ms per loop


In [25]:
#np.max()
#np.min()

In [27]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.max(a)
max([[1,2,3],[4,1,1],[1,8,9],[8,2,3]])

[8, 2, 3]

In [39]:

np.max(a, axis=1)

array([ 2,  7, 11])

In [41]:
a

array([[ 0,  1,  2,  1],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a[0][3] =1
np.max(a, axis=1)

array([ 2,  7, 11])

#집계함수

In [44]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a[0][0] = 100
np.mean(a) #평균

13.833333333333334

In [48]:
np.median(a) #중앙값

6.5

In [49]:
np.std(a) #표준편차

26.15604880116431

In [50]:
np.var(a) #분산

684.138888888889

In [51]:
np.sum(a) #합

166